app.database.url = jdbc:mysql://localhost:3306/testserviceonededevv
app.database.username=rajuserviceonedev--confidential--********12345
app.database.password=rajuserviceonedev--confidential--********12345